### ISSUE TITLE
ERROR: aom >= 1.0.0 not found using pkg-config

### ISSUE THREAD

**Issue by frozenpandaman** [deus0ww/homebrew-tap#1]
Hi, thanks for maintaining these formulae! I'm following your instructions from this comment: https://github.com/mpv-player/mpv/issues/9232#issuecomment-925922864 My goal is to install a cask (.app) version of mpv that is built for ARM/M1 Macs.

In running `brew install --HEAD deus0ww/tap/mpv`, I had to uninstall `ffmpeg` (which I had previously installed) as your mpv formula requires the version of ffmpeg from your tap. So I did this, but now I'm getting the following error as it tries to install the deus0ww/tap/ffmpeg dependency:
```
ERROR: aom >= 1.0.0 not found using pkg-config
```

`aom.pc` is present in /opt/homebrew/lib/pkgconfig and it's version 3.2.0 – running `brew info aom` confirms it's installed – so I'm not sure what the issue is. Any ideas?

**Comment by frozenpandaman** [comment]
In effort to avoid this, per your comment _"If you want to use the normal formulas these (from homebrew-core), you'll need to clone the tap and modify it yourself"_ – I did this, and it built, but now it's crashing upon launch, thinking it can't find some libraries, which for some reason it seems to be looking for in /usr/local rather than /opt/homebrew:
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/lib/libvmaf.1.dylib
Referenced from: /opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libavcodec.58.dylib
Reason: tried: '/opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libvmaf.1.dylib' (no such file), '/usr/local/lib/libvmaf.1.dylib' (no such file), '/usr/lib/libvmaf.1.dylib' (no such file)Library not loaded: @executable_path/lib/libvmaf.1.dylib
Referenced from: /opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libavformat.58.dylib
Reason: tried: '/opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libvmaf.1.dylib' (no such file), '/usr/local/lib/libvmaf.1.dylib' (no such file), '/usr/lib/libvmaf.1.dylib' (no such file)Library not loaded: @executable_path/lib/libvmaf.1.dylib
Referenced from: /opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libavfilter.7.dylib
Reason: tried: '/opt/homebrew/Cellar/mpv/HEAD-c478a1e/mpv.app/Contents/MacOS/lib/libvmaf.1.dylib' (no such file), '/usr/local
(terminated at launch; ignore backtrace)
```

**Comment by frozenpandaman** [comment]
I solved it! This is not at all the ideal way – it's very… manual – and in fact it doesn't use your tap at all, but commenting here in case it helps others who stumble upon trying to make an ARM64/M1 Mac build of mpv:

1. `brew install mpv`
2. Clone the https://github.com/mpv-player/mpv repo
3. Create an empty `build/` folder inside that repo
3. Take the `opt/homebrew/bin/mpv` binary from step 1 and copy it to the `build/` folder
4. Edit line 11 of `TOOLS/dylib-unhell.py` to say `/opt/homebrew/` (instead of the old `/usr/lib/` path)
5. Run `python TOOLS/osxbundle.py build/mpv`
6. Drag the resulting `build/mpv.app` to your Applications folder, or wherever you want

**Comment by deus0ww** [comment]
The problem is the homebrew-core formula for 'aom' is also !@#$ed.

See:
https://github.com/mpv-player/mpv/pull/9334
https://github.com/Homebrew/homebrew-core/pull/87742

To solve this, I had to modify the 'aom' formula, too, so it doesn't include the problematic dependency to 'brotli'.  To install from my tap, you would need to uninstall ffmpeg and aom from homebrew-core.
