### ISSUE TITLE
cannot enable macvk

### ISSUE THREAD

**Issue by hooke007** [deus0ww/homebrew-tap#12]
https://github.com/mpv-player/mpv/commit/78d43740f52db817d98bcf24fb30a76ab6fa13ff

In theory, this could work `--vo=gpu --gpu-context=macvk` . But currently it just throws an error message.
```
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the VO window.
```

Did it miss any dependency?

**Comment by deus0ww** [comment]
I'm looking into it now... lol

**Comment by deus0ww** [comment]
Seems to work with shaderc.

**Comment by hooke007** [comment]
Emm... uninstall mpv libplacebo ffmpeg and then reinstalled them.
Not work here.

**Comment by deus0ww** [comment]
I also installed molten-vk from homebrew and vulkan-sdk from https://vulkan.lunarg.com/sdk/home

**Comment by hooke007** [comment]
@deus0ww I found a patch from one of mpv dev's branch. It allows native hwdec on apple silicon.
https://github.com/rcombs/mpv/commit/fd1f9a2051741f7f44c1000b0d35304d6e8f041f

**Comment by deus0ww** [comment]
I can't test today but, for clarity, are you talking about hwdec=vulkan or hwdec=videotoolbox?

**Comment by hooke007** [comment]
`hwdec=videotoolbox`

**Comment by deus0ww** [comment]
Nice... When I tested yesterday, only videotoolbox-copy worked. I hope rcomb gets that merged soon.

**Comment by deus0ww** [comment]
@hooke007 I added m154k1's patches to the mpv formula.  hwdec should work...

**Comment by hooke007** [comment]
> I hope rcomb gets that merged soon.

It's coming. https://github.com/mpv-player/mpv/pull/12776

**Comment by hooke007** [comment]
patch 3 seems to be unnecessary.
https://github.com/mpv-player/mpv/pull/12846
