### ISSUE TITLE
Cannot compile ffmpeg

### ISSUE THREAD

**Issue by okand** [deus0ww/homebrew-tap#13]
I am trying to compile mpv using your tap in order to get an app-bundle that's native to apple silicon but it stops on the way while compiling ffmpeg. It stops with the following error:
```
libavfilter/vf_libplacebo.c:429:14: error: field designator 'overshoot_margin' does not refer to any field in type 'struct pl_peak_detect_params'
            .overshoot_margin = s->overshoot,
             ^
1 error generated.
make: *** [libavfilter/vf_libplacebo.o] Error 1
make: *** Waiting for unfinished jobs....
```
Not sure how to proceed myself, is this perhaps something wrong with the code for either ffmpeg or libplacebo and I just need to wait for someone upstream?

Full output with the verbose flag in the attached file since it is very long and would just get in the way reading the thread.
[brewlog.txt](https://github.com/deus0ww/homebrew-tap/files/13023007/brewlog.txt)

**Comment by deus0ww** [comment]
For libplacebo and ffmpeg, use HEAD with "brew install --head ...".  I would also use HEAD version of mpv.

**Comment by okand** [comment]
Thank you!

It wasn't represented in the log but I was trying to install mpv with the `--HEAD` flag already, thus I assumed any dependencies would be done that way too if necessary.

Installing ffmpeg on its own with `--HEAD` worked. It still didn't get me all the way to a working install of mpv though :(

It stops while trying to install dockutil@3 now.
```
==> Installing deus0ww/tap/mpv dependency: deus0ww/tap/dockutil@3
==> Patching
==> swift build --disable-sandbox --configuration release
Last 15 lines from /Users/alexander/Library/Logs/Homebrew/dockutil@3/01.swift:
2023-10-18 13:29:36 +0000

swift
build
--disable-sandbox
--configuration
release

error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'


If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/deus0ww/homebrew-tap/issues
```

**Comment by okand** [comment]
This was googlable and probably some kind of leftover from having run the sonoma beta for a bit. After running `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer` to change the SDK location it worked and I now have an mpv .app-bundle as I wanted.
