### ISSUE TITLE
Sometimes the line doesn't work.

### ISSUE THREAD

**Issue by hooke007** [deus0ww/homebrew-tap#16]
https://github.com/deus0ww/homebrew-tap/blob/e069e30abbc1068c0d5b5952fb31a7115a188dc0/mpv.rb#L133

Any ideas?

**Comment by deus0ww** [comment]
No idea. This has never failed for me before. Is there any log? If not, try removing "--allhomes".

**Comment by hooke007** [comment]
No log. No clue...
