### ISSUE TITLE
What kind of question is that？

### ISSUE THREAD

**Issue by icewindwillow** [deus0ww/homebrew-tap#3]
icewind@Icewind-MBP ~ % brew install --HEAD deus0ww/tap/mpv 
HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.ustc.edu.cn/brew.git for Homebrew/brew Git remote.
==> Cloning https://github.com/mpv-player/mpv.git
Updating /Users/icewind/Library/Caches/Homebrew/mpv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 3458651010 stream_lavf: add support for ipfs and ipns
==> Installing mpv from deus0ww/tap
==> /opt/homebrew/opt/python@3.10/bin/python3 bootstrap.py
==> /opt/homebrew/opt/python@3.10/bin/python3 waf configure --prefix=/opt/homebrew/Cellar/mpv/HEAD-3458651 --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv/HEAD-3458651/share/mpv --docdi
==> /opt/homebrew/opt/python@3.10/bin/python3 waf install
Last 15 lines from /Users/icewind/Library/Logs/Homebrew/mpv/03.python3:
  "_jpeg_start_compress", referenced from:
      _write_jpeg in lto.o
  "_jpeg_write_scanlines", referenced from:
      _write_jpeg in lto.o
  "_jpeg_finish_compress", referenced from:
      _write_jpeg in lto.o
  "_jpeg_destroy_compress", referenced from:
      _write_jpeg in lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/private/tmp/mpv-20220508-17153-1hc82a7/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

**Comment by deus0ww** [comment]
mpv is building fine for me on 10.14 (intel) and 12.x (m1).  This seems like a toolchain problem on your end.
