### ISSUE TITLE
Suggestion: Added JPEG XL

### ISSUE THREAD

**Issue by eko5624** [deus0ww/homebrew-tap#4]
Now mpv can decode jpeg-jxl and support .jxl screenshot, so enable-libjxl.

**Comment by deus0ww** [comment]
Many months ago there were issues with building with aom and jpen-xl (in ffmpeg and in mpv). I'll try including them again when I have time.

**Comment by deus0ww** [comment]
Done.

**Comment by eko5624** [comment]
@deus0ww Didn't work. When I open a .jxl file, mpv crashed. Please take a look.

**Comment by eko5624** [comment]
Should enable-libjxl in ffmpeg, not in mpv?

**Comment by deus0ww** [comment]
ffmpeg: ERROR:  >= 0.7.0 not found using pkg-config

The current release is 0.6.1.  We'll probably have to wait for release.

**Comment by eko5624** [comment]
@deus0ww  Compile libjxl head should work.

**Comment by deus0ww** [comment]
I know but I can't change the brew formula based on head builds. You can fork this repo, add edited jpeg-xl, and replicate all formulas that depends on jpeg-xl from homebrew-core.

**Comment by deus0ww** [comment]
jpeg-xl is now an optional dependency. Install jpeg-xl head before installing ffmpeg with it enabled.

**Comment by eko5624** [comment]
I compile libjxl head on my mac. When run "./TOOLS/osxbundle.py build/mpv" , errors like this:
```
Creating Mac OS X application bundle (version: 0.34.0-UNKNOWN)...
> copying bundle skeleton
> copying binary
> create bundle symlink
> generating Info.plist
> bundling dependencies
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: @rpath/libjxl_threads.0.7.dylib (No such file or directory)
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: @rpath/libjxl.0.7.dylib (No such file or directory)
```

**Comment by deus0ww** [comment]
Are you using homebrew?

It should be something like:
brew install jpeg-xl --head
brew install deus0ww/tap/ffmpeg
brew install deus0ww/tap/mpv

I should note that I haven't tested it myself....

**Comment by eko5624** [comment]
This is how I compile libjxl:
```
git clone https://github.com/libjxl/libjxl.git /Volumes/USB/Downloads/libjxl
cd libjxl
git submodule update --init --recursive --depth 1 --recommend-shallow third_party/{brotli,highway,skcms}
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/Volumes/USB/Downloads -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DJPEGXL_EMSCRIPTEN=OFF -DJPEGXL_BUNDLE_LIBPNG=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_DOXYGEN=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_DEVTOOLS=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_SJPEG=OFF ..
cmake --build .
cmake --install . --prefix=/Volumes/USB/Downloads
```

**Comment by deus0ww** [comment]
If you're not using homebrew to manage dependencies, I can't help you. Try asking on mpv's irc.

**Comment by deus0ww** [comment]
This is now working for me. Do this:
- Uninstall ffmpeg, aom, jpeg-xl, mpv
- brew install deus0ww/tap/jpeg-xl --head
- brew install deus0ww/tap/ffmpeg
- brew install deus0ww/tap/mpv

Note that I tested this on macOS 10.14 on Intel and 12 on M1 with ffmpeg head and mpv head.

**Comment by eko5624** [comment]
Can you pull a PR to mpv repo. I want to download mpv source code and compile. 
In dylib-unhell.py, original is: 
```
libraries(lib, result)
```

If I edit it, what it should be, thanks.

**Comment by deus0ww** [comment]
No. What I did is an ugly hack that only works with homebrew installed dependencies. It certainly should not be in the mpv source. If you're not using homebrew, my workaround is not going to help you in any way.

**Comment by eko5624** [comment]
I'm not a coder, sorry for this simple question. After running the code below, what "libraries(lib, result)" will change to? 
```
inreplace "TOOLS/dylib-unhell.py", "libraries(lib, result)", "lib = lib.replace(\"@loader_path\", \"" + "#{HOMEBREW_PREFIX}/lib" + "\"); libraries(lib, result)"
```

**Comment by deus0ww** [comment]
lib = lib.replace("@loader_path", "LOCATION_OF_LIB"); libraries(lib, result)

**Comment by eko5624** [comment]
In my repo

This works:
https://github.com/eko5624/mpv-macos-intel/blob/c92345614310b329b3b0fa34ba70505b3fb7619b/.github/workflows/build.yml#L60

This works:
```
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlienc.1.dylib
```

This doesn't work.
```
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "${HOMEBREW_PREFIX}/lib/libbrotlicommon.1.dylib" "${HOMEBREW_PREFIX}/lib/libbrotlidec.1.dylib"
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "${HOMEBREW_PREFIX}/lib/libbrotlicommon.1.dylib" "${HOMEBREW_PREFIX}/lib/libbrotlienc.1.dylib"
```
error log like this:
error: /Applications/Xcode_13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /lib/libbrotlidec.1.dylib (No such file or directory)

If I use HOMEBREW_PREFIX variable in TOOLS/dylib-unhell.py, how to edit it?

**Comment by deus0ww** [comment]
You know Homebrew has documentation, right? Maybe you should try reading it sometime.

$(brew --prefix)

**Comment by eko5624** [comment]
I edit dylib-unhell.py like this, but didn't work. 
```
    for lib in libs_list:
        if lib not in result:
            lib = lib.replace("@loader_path", "$(brew --prefix)/lib"); libraries(lib, result)
```
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: $(brew --prefix)/lib/libbrotlicommon.1.dylib (No such file or directory)
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: $(brew --prefix)/lib/libbrotlicommon.1.dylib (No such file or directory)

But this works:
```
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlidec.1.dylib"
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlienc.1.dylib"
```
Why?

**Comment by deus0ww** [comment]
Because one is in a python script and the other is in the shell. If you don't know understand that, figure it out yourself.

**Comment by eko5624** [comment]
Got it, thanks.
