### ISSUE TITLE
Suggestion: Add an option to libass 

### ISSUE THREAD

**Issue by toooonyy** [deus0ww/homebrew-tap#5]
Coretext selection seems to be based on PostScript name but many .ass files are using full name, building libass with fontconfig fixed this. 
My current workaround is to using `brew edit` to change the formula locally. So is it possible to re-add this `--with-fontconfig` flag and disable by default(so the default behavior doesn't change)?

**Comment by deus0ww** [comment]
I added fontconfig as an optional dependency. This is untested. Please try.

**Comment by toooonyy** [comment]
Thanks, all working now.
