### ISSUE TITLE
rubberband compiling failed

### ISSUE THREAD

**Issue by eko5624** [deus0ww/homebrew-tap#7]
../meson.build:539:0: ERROR: Include dir /Library/Java/JavaVirtualMachines/Current/Contents/Home/include does not exist.

Any ideas?

**Comment by LampPrinter** [comment]
> ../meson.build:539:0: ERROR: Include dir /Library/Java/JavaVirtualMachines/Current/Contents/Home/include does not exist.
> 
> Any ideas?

I think you need to replace "Current" with whatever java you have in "/Library/Java/JavaVirtualMachines/"
For instance I have zulu-19.jdk

But it still failed for me after that. 

glsl/glslang.cc:213:21: error: excess elements in scalar initializer
    /* .limits = */ {

I am using this to compile a native ARM version.
https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f

**Comment by eko5624** [comment]
@LampPrinter Can this solve your issue?`brew install deus0ww/tap/libplacebo --HEAD`

**Comment by eko5624** [comment]
I use GHA to compile mpv, this fix my issue:
```
sudo mkdir -p /Library/Java/JavaVirtualMachines/Current/Contents/Home
sudo cp -r ${JAVA_HOME_17_X64}* /Library/Java/JavaVirtualMachines/Current/Contents/Home
```
My repo:
https://github.com/eko5624/mpv-macos-test/blob/deus0ww-tap/.github/workflows/build.yml

**Comment by LampPrinter** [comment]
I cann't seem to build it. Why not just release an ARM version on your github :)

**Comment by eko5624** [comment]
Yes, it can build successfully.
Because there's no M1(ARM-based) virtual environment runner, so can't support Macos-arm64. 
You can use self-hosted runners on your M1 machine to build. 

https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

**Comment by deus0ww** [comment]
The customized rubberband formula is no longer needed as the issue I was working around has been fixed.
